import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path) => readFileSync(path, "utf8");
const sync = read("src/lib/blossom/sync.server.ts");
const syncTypes = read("src/lib/blossom/sync-types.ts");
const integrity = read("src/lib/blossom/activity-integrity.server.ts");
const bootstrap = read("src/lib/auth/admin-bootstrap.ts");
const gate = read("src/lib/auth/gate-session.server.ts");
const auth = read("src/lib/auth/server.ts");
const rateLimit = read("src/lib/blossom/rate-limit.server.ts");
const preview = read("src/lib/auth/preview.ts");
const api = read("src/lib/blossom/api.ts");
const domain = read("src/lib/blossom/domain.server.ts");
const safety = read("src/lib/blossom/safety.server.ts");
const messaging = read("src/lib/blossom/messaging.server.ts");
const domainApi = read("src/lib/blossom/domain.api.ts");
const speakServer = read("src/lib/blossom/speak-server.server.ts");
const pwa = read("server/middleware/grok-pwa.ts");

test("activity mutations are enum-gated and pass through server integrity checks", () => {
  assert.match(sync, /eventType: z\.enum\(ACTIVITY_EVENT_TYPES\)/);
  assert.match(sync, /await assertActivityAppend\(/);
  assert.match(integrity, /activity-mastery-server-only/);
  assert.match(integrity, /activity-diagnostic-server-only/);
  assert.match(integrity, /activity-tandem-insufficient-evidence/);
  assert.match(read("src/lib/blossom/backend.server.ts"), /where blossom_learning_submission\.user_id = excluded\.user_id/);
  assert.match(read("src/lib/blossom/domain.server.ts"), /where blossom_learning_submission\.user_id = excluded\.user_id/);
  assert.match(integrity, /activity-event-without-attendance/);
  assert.match(integrity, /activity-pronlab-without-attempt/);
  assert.match(integrity, /tandem-session-/);
  assert.match(integrity, /activity-language-mismatch/);
  assert.match(sync, /activeLanguageId/);
  assert.match(sync, /targetLanguage: z\.enum/);
  assert.match(integrity, /mission-completion-without-prior-session/);
  assert.match(sync, /assertMissionSessionMutation/);
  assert.match(sync, /mutation\.deviceId !== deviceId/);
  assert.match(sync, /MAX_FUTURE_MUTATION_SKEW_MS/);
  assert.match(sync, /invalid-mutation-time/);
  assert.match(sync, /insert into blossom_sync_device/);
  assert.match(api, /z\.enum\(ACTIVITY_EVENT_TYPES\)/);
  assert.match(api, /await assertActivityAppend\(/);
  assert.match(api, /await assertMissionSessionMutation\(/);
  assert.match(api, /enforceRateLimit\(context\.userId, "activity\.append"/);
  assert.match(api, /enforceRateLimit\(context\.userId, "mission\.save"/);
  assert.match(api, /enforceRateLimit\(context\.userId, "profile\.upsert"/);
  assert.match(integrity, /activity-library-unknown-source/);
  assert.match(integrity, /activity-library-without-reading/);
  assert.match(integrity, /library-reading-too-fast/);
  assert.match(integrity, /assertLibraryReadingMutation/);
  assert.match(syncTypes, /"library.start"/);
  assert.match(syncTypes, /"library.complete"/);
  assert.match(sync, /case "library.start"/);
  assert.match(sync, /case "library.complete"/);
  assert.match(sync, /review-pron-without-attempt/);
  assert.match(sync, /review-vocab-without-word/);
  assert.match(sync, /unknown-review-source/);
  assert.match(integrity, /activity-pulse-unknown-source/);
  assert.match(integrity, /activity-review-invalid-source/);
  assert.match(integrity, /activity-legacy-reward-server-only/);
  assert.match(integrity, /mission-completion-adds-unrelated-run/);
  assert.match(speakServer, /speak\.room/);
  assert.doesNotMatch(speakServer, /userWindows/);
  assert.doesNotMatch(speakServer, /function assertRateLimit\(userId: string\)/);
  assert.match(pwa, /withSecurityHeaders\(result, event\)/);
  assert.match(safety, /tandem_connection mine/);
  assert.match(safety, /mine\.status = 'accepted'/);
  assert.match(safety, /Vous ne pouvez signaler qu'un tandem réciproquement accepté/);
  assert.match(messaging, /communication\.list/);
  assert.match(messaging, /order by c\.updated_at desc limit 100/);
  assert.match(messaging, /await assertConversationAccess\(userId, conversationId\)/);
  assert.match(domain, /commerce\.booking-request/);
  assert.match(domain, /commerce\.waitlist-request/);
  assert.match(domain, /learning\.pronlab-attempt/);
  assert.match(domain, /learning\.vocabulary-upsert/);
  assert.match(domain, /tandem\.status/);
  assert.match(domain, /event\.register/);
  assert.match(domain, /immersion\.challenge-complete/);
  assert.match(domain, /teacher\.homework-save/);
  assert.match(domain, /teacher\.note-save/);
  assert.match(domain, /homework\.complete/);
  assert.match(domain, /learning\.submission/);
  assert.match(domain, /admin\.booking-update/);
  assert.match(domain, /communication\.connect-peers/);
  assert.match(domain, /tandem\.candidates/);
  assert.match(domain, /order by display_name asc\n    limit 100/);
  assert.match(domain, /m\.role <> 'learner'/);
  assert.match(domain, /g\.teacher_user_id = \$2/);
  assert.match(sync, /updated_at < current_timestamp - interval '5 minutes'/);
  assert.match(domain, /duration_seconds = greatest/);
  assert.match(domain, /durationSeconds: Math\.max/);
  assert.match(read("migrations/0029_tandem_session_integrity.sql"), /create unique index if not exists blossom_tandem_session_active_pair_uidx/);
  assert.match(read("migrations/0029_tandem_session_integrity.sql"), /alter table blossom_tandem_session/);
  assert.match(domainApi, /ensureBootstrapAdmin\(context\.userId, identity\.email, identity\.emailVerified\)/);
});

test("authenticated abuse surfaces use the distributed Postgres limiter", () => {
  assert.match(sync, /enforceRateLimit\(userId, "sync\.batch"/);
  assert.match(rateLimit, /on conflict \(user_id, bucket_key\) do update/);
  assert.match(rateLimit, /hit_count < \$4/);
  assert.match(read("src/lib/blossom/messaging.server.ts"), /communication\.send/);
  assert.match(read("src/lib/blossom/messaging.server.ts"), /communication\.report/);
  assert.match(read("src/lib/blossom/safety.server.ts"), /safety\.tandem-report/);
  assert.match(read("src/lib/blossom/speech-server.server.ts"), /speech\.transcribe/);
  assert.match(read("src/lib/blossom/domain.server.ts"), /tandem\.end-session/);
});

test("Better Auth uses persistent rate limiting and stronger password floor", () => {
  assert.match(auth, /storage: "database"/);
  assert.match(auth, /minPasswordLength: 12/);
  assert.match(auth, /"\/sign-in\/email": \{ window: 10, max: 5 \}/);
});

test("production admin bootstrap fails closed and session material is never logged", () => {
  assert.match(bootstrap, /if \(hasRealDatabase\(\)\) return \[\];/);
  assert.doesNotMatch(gate, /cookiePreview/);
  assert.match(preview, /GROK_PREVIEW_CLIENT_SECRET/);
  assert.doesNotMatch(preview, /PREVIEW_CLIENT_SECRET\\s*=\\s*["']/);
});

test("the custom rate-limit error is explicit 429", () => {
  assert.match(rateLimit, /readonly status = 429/);
});
