/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppConnectRouteImport } from './routes/_app/connect'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppImmersionRouteImport } from './routes/_app/immersion'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppLearnRouteImport } from './routes/_app/learn'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppMissionRouteImport } from './routes/_app/mission'
import { Route as AppMoiRouteImport } from './routes/_app/moi'
import { Route as AppOsezRouteImport } from './routes/_app/osez'
import { Route as AppPlantRouteImport } from './routes/_app/plant'
import { Route as AppPronlabRouteImport } from './routes/_app/pronlab'
import { Route as AppTandemRouteImport } from './routes/_app/tandem'
import { Route as AppLibraryIdRouteImport } from './routes/_app/library.$id'
import { Route as AppOsezIdRouteImport } from './routes/_app/osez.$id'
import { Route as AppOsezPulseRouteImport } from './routes/_app/osez.pulse'
import { Route as AppPronlabSetIdRouteImport } from './routes/_app/pronlab.$setId'
import { Route as AppTandemIdRouteImport } from './routes/_app/tandem.$id'
import { Route as AppLearnCurriculumRouteImport } from './routes/_app/learn.curriculum'
import { Route as AppLearnCurriculumUnitIdRouteImport } from './routes/_app/learn.curriculum.$unitId'
import { Route as AppLearnReviewRouteImport } from './routes/_app/learn.review'
import { Route as AppLearnProgressRouteImport } from './routes/_app/learn.progress'
import { Route as AppLearnHistoryRouteImport } from './routes/_app/learn.history'
import { Route as AppLearnLabsRouteImport } from './routes/_app/learn.labs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAuthRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppImmersionRoute = AppImmersionRouteImport.update({
  id: '/immersion',
  path: '/immersion',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionRoute = AppMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AppRoute,
} as any)
const AppMoiRoute = AppMoiRouteImport.update({
  id: '/moi',
  path: '/moi',
  getParentRoute: () => AppRoute,
} as any)
const AppOsezRoute = AppOsezRouteImport.update({
  id: '/osez',
  path: '/osez',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantRoute = AppPlantRouteImport.update({
  id: '/plant',
  path: '/plant',
  getParentRoute: () => AppRoute,
} as any)
const AppPronlabRoute = AppPronlabRouteImport.update({
  id: '/pronlab',
  path: '/pronlab',
  getParentRoute: () => AppRoute,
} as any)
const AppTandemRoute = AppTandemRouteImport.update({
  id: '/tandem',
  path: '/tandem',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIdRoute = AppLibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppOsezIdRoute = AppOsezIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOsezRoute,
} as any)
const AppOsezPulseRoute = AppOsezPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => AppOsezRoute,
} as any)
const AppPronlabSetIdRoute = AppPronlabSetIdRouteImport.update({
  id: '/$setId',
  path: '/$setId',
  getParentRoute: () => AppPronlabRoute,
} as any)
const AppTandemIdRoute = AppTandemIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTandemRoute,
} as any)
const AppLearnCurriculumRoute = AppLearnCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AppLearnRoute,
} as any)
const AppLearnCurriculumUnitIdRoute = AppLearnCurriculumUnitIdRouteImport.update({
  id: '/curriculum/$unitId',
  path: '/curriculum/$unitId',
  getParentRoute: () => AppLearnCurriculumRoute,
} as any)
const AppLearnReviewRoute = AppLearnReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppLearnRoute,
} as any)
const AppLearnProgressRoute = AppLearnProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppLearnRoute,
} as any)
const AppLearnHistoryRoute = AppLearnHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppLearnRoute,
} as any)
const AppLearnLabsRoute = AppLearnLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AppLearnRoute,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/connect': typeof AppConnectRoute
  '/explore': typeof AppExploreRoute
  '/immersion': typeof AppImmersionRoute
  '/learn': typeof AppLearnRouteWithChildren
  '/learn/curriculum': typeof AppLearnCurriculumRoute
  '/learn/curriculum/$unitId': typeof AppLearnCurriculumUnitIdRoute
  '/learn/review': typeof AppLearnReviewRoute
  '/learn/progress': typeof AppLearnProgressRoute
  '/learn/history': typeof AppLearnHistoryRoute
  '/learn/labs': typeof AppLearnLabsRoute
  '/library': typeof AppLibraryRouteWithChildren
  '/mission': typeof AppMissionRoute
  '/inbox': typeof AppInboxRoute
  '/moi': typeof AppMoiRoute
  '/osez': typeof AppOsezRouteWithChildren
  '/osez/pulse': typeof AppOsezPulseRoute
  '/plant': typeof AppPlantRoute
  '/pronlab': typeof AppPronlabRouteWithChildren
  '/tandem': typeof AppTandemRouteWithChildren
  '/library/$id': typeof AppLibraryIdRoute
  '/osez/$id': typeof AppOsezIdRoute
  '/pronlab/$setId': typeof AppPronlabSetIdRoute
  '/tandem/$id': typeof AppTandemIdRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthRoute
}
export interface FileRoutesByTo {
  '/connect': typeof AppConnectRoute
  '/explore': typeof AppExploreRoute
  '/immersion': typeof AppImmersionRoute
  '/learn': typeof AppLearnRouteWithChildren
  '/learn/curriculum': typeof AppLearnCurriculumRoute
  '/learn/curriculum/$unitId': typeof AppLearnCurriculumUnitIdRoute
  '/learn/review': typeof AppLearnReviewRoute
  '/learn/progress': typeof AppLearnProgressRoute
  '/learn/history': typeof AppLearnHistoryRoute
  '/learn/labs': typeof AppLearnLabsRoute
  '/library': typeof AppLibraryRouteWithChildren
  '/mission': typeof AppMissionRoute
  '/moi': typeof AppMoiRoute
  '/osez': typeof AppOsezRouteWithChildren
  '/osez/pulse': typeof AppOsezPulseRoute
  '/plant': typeof AppPlantRoute
  '/pronlab': typeof AppPronlabRouteWithChildren
  '/tandem': typeof AppTandemRouteWithChildren
  '/': typeof AppIndexRoute
  '/library/$id': typeof AppLibraryIdRoute
  '/osez/$id': typeof AppOsezIdRoute
  '/pronlab/$setId': typeof AppPronlabSetIdRoute
  '/tandem/$id': typeof AppTandemIdRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/connect': typeof AppConnectRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/immersion': typeof AppImmersionRoute
  '/_app/learn': typeof AppLearnRouteWithChildren
  '/_app/learn/curriculum': typeof AppLearnCurriculumRoute
  '/_app/learn/curriculum/$unitId': typeof AppLearnCurriculumUnitIdRoute
  '/_app/learn/review': typeof AppLearnReviewRoute
  '/_app/learn/progress': typeof AppLearnProgressRoute
  '/_app/learn/history': typeof AppLearnHistoryRoute
  '/_app/learn/labs': typeof AppLearnLabsRoute
  '/_app/library': typeof AppLibraryRouteWithChildren
  '/_app/mission': typeof AppMissionRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/moi': typeof AppMoiRoute
  '/_app/osez': typeof AppOsezRouteWithChildren
  '/_app/osez/pulse': typeof AppOsezPulseRoute
  '/_app/plant': typeof AppPlantRoute
  '/_app/pronlab': typeof AppPronlabRouteWithChildren
  '/_app/tandem': typeof AppTandemRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/library/$id': typeof AppLibraryIdRoute
  '/_app/osez/$id': typeof AppOsezIdRoute
  '/_app/pronlab/$setId': typeof AppPronlabSetIdRoute
  '/_app/tandem/$id': typeof AppTandemIdRoute
  '/_app/learn/curriculum': typeof AppLearnCurriculumRoute
  '/_app/learn/curriculum/$unitId': typeof AppLearnCurriculumUnitIdRoute
  '/_app/learn/review': typeof AppLearnReviewRoute
  '/_app/learn/progress': typeof AppLearnProgressRoute
  '/_app/learn/history': typeof AppLearnHistoryRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/explore'
    | '/immersion'
    | '/learn'
    | '/library'
    | '/mission'
    | '/inbox'
    | '/moi'
    | '/osez'
    | '/osez/pulse'
    | '/plant'
    | '/pronlab'
    | '/tandem'
    | '/library/$id'
    | '/osez/$id'
    | '/pronlab/$setId'
    | '/tandem/$id'
    | '/learn/curriculum'
    | '/learn/curriculum/$unitId'
    | '/learn/review'
    | '/learn/progress'
    | '/learn/history'
    | '/learn/labs'
    | '/login'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connect'
    | '/explore'
    | '/immersion'
    | '/learn'
    | '/library'
    | '/mission'
    | '/moi'
    | '/osez'
    | '/osez/pulse'
    | '/plant'
    | '/pronlab'
    | '/tandem'
    | '/'
    | '/library/$id'
    | '/osez/$id'
    | '/pronlab/$setId'
    | '/tandem/$id'
    | '/learn/curriculum'
    | '/learn/curriculum/$unitId'
    | '/learn/review'
    | '/learn/progress'
    | '/learn/history'
    | '/learn/labs'
    | '/login'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/_app/connect'
    | '/_app/explore'
    | '/_app/immersion'
    | '/_app/learn'
    | '/_app/learn/curriculum'
    | '/_app/learn/curriculum/$unitId'
    | '/_app/learn/review'
    | '/_app/learn/progress'
    | '/_app/learn/history'
    | '/_app/learn/labs'
    | '/_app/library'
    | '/_app/mission'
    | '/_app/inbox'
    | '/_app/moi'
    | '/_app/osez'
    | '/_app/osez/pulse'
    | '/_app/plant'
    | '/_app/pronlab'
    | '/_app/tandem'
    | '/_app/'
    | '/_app/library/$id'
    | '/_app/osez/$id'
    | '/_app/pronlab/$setId'
    | '/_app/tandem/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthRoute: typeof ApiAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/immersion': {
      id: '/_app/immersion'
      path: '/immersion'
      fullPath: '/immersion'
      preLoaderRoute: typeof AppImmersionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn/curriculum': {
      id: '/_app/learn/curriculum'
      path: '/curriculum'
      fullPath: '/learn/curriculum'
      preLoaderRoute: typeof AppLearnCurriculumRouteImport
      parentRoute: typeof AppLearnRoute
    }
    '/_app/learn/curriculum/$unitId': {
      id: '/_app/learn/curriculum/$unitId'
      path: '/curriculum/$unitId'
      fullPath: '/learn/curriculum/$unitId'
      preLoaderRoute: typeof AppLearnCurriculumUnitIdRouteImport
      parentRoute: typeof AppLearnRoute
    }
    '/_app/learn/review': {
      id: '/_app/learn/review'
      path: '/review'
      fullPath: '/learn/review'
      preLoaderRoute: typeof AppLearnReviewRouteImport
      parentRoute: typeof AppLearnRoute
    }
    '/_app/learn/progress': {
      id: '/_app/learn/progress'
      path: '/progress'
      fullPath: '/learn/progress'
      preLoaderRoute: typeof AppLearnProgressRouteImport
      parentRoute: typeof AppLearnRoute
    }
    '/_app/learn/history': {
      id: '/_app/learn/history'
      path: '/history'
      fullPath: '/learn/history'
      preLoaderRoute: typeof AppLearnHistoryRouteImport
      parentRoute: typeof AppLearnRoute
    }
    '/_app/learn/labs': {
      id: '/_app/learn/labs'
      path: '/labs'
      fullPath: '/learn/labs'
      preLoaderRoute: typeof AppLearnLabsRouteImport
      parentRoute: typeof AppLearnRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mission': {
      id: '/_app/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof AppMissionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/moi': {
      id: '/_app/moi'
      path: '/moi'
      fullPath: '/moi'
      preLoaderRoute: typeof AppMoiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/osez': {
      id: '/_app/osez'
      path: '/osez'
      fullPath: '/osez'
      preLoaderRoute: typeof AppOsezRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plant': {
      id: '/_app/plant'
      path: '/plant'
      fullPath: '/plant'
      preLoaderRoute: typeof AppPlantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pronlab': {
      id: '/_app/pronlab'
      path: '/pronlab'
      fullPath: '/pronlab'
      preLoaderRoute: typeof AppPronlabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tandem': {
      id: '/_app/tandem'
      path: '/tandem'
      fullPath: '/tandem'
      preLoaderRoute: typeof AppTandemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/$id': {
      id: '/_app/library/$id'
      path: '/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof AppLibraryIdRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/_app/osez/$id': {
      id: '/_app/osez/$id'
      path: '/$id'
      fullPath: '/osez/$id'
      preLoaderRoute: typeof AppOsezIdRouteImport
      parentRoute: typeof AppOsezRoute
    }
    '/_app/osez/pulse': {
      id: '/_app/osez/pulse'
      path: '/pulse'
      fullPath: '/osez/pulse'
      preLoaderRoute: typeof AppOsezPulseRouteImport
      parentRoute: typeof AppOsezRoute
    }
    '/_app/pronlab/$setId': {
      id: '/_app/pronlab/$setId'
      path: '/$setId'
      fullPath: '/pronlab/$setId'
      preLoaderRoute: typeof AppPronlabSetIdRouteImport
      parentRoute: typeof AppPronlabRoute
    }
    '/_app/tandem/$id': {
      id: '/_app/tandem/$id'
      path: '/$id'
      fullPath: '/tandem/$id'
      preLoaderRoute: typeof AppTandemIdRouteImport
      parentRoute: typeof AppTandemRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppLearnRouteChildren {
  AppLearnCurriculumRoute: typeof AppLearnCurriculumRouteWithChildren
  AppLearnReviewRoute: typeof AppLearnReviewRoute
  AppLearnProgressRoute: typeof AppLearnProgressRoute
  AppLearnHistoryRoute: typeof AppLearnHistoryRoute
  AppLearnLabsRoute: typeof AppLearnLabsRoute
}

const AppLearnRouteChildren: AppLearnRouteChildren = {
  AppLearnCurriculumRoute: AppLearnCurriculumRouteWithChildren,
  AppLearnReviewRoute: AppLearnReviewRoute,
  AppLearnProgressRoute: AppLearnProgressRoute,
  AppLearnHistoryRoute: AppLearnHistoryRoute,
  AppLearnLabsRoute: AppLearnLabsRoute,
}

const AppLearnRouteWithChildren = AppLearnRoute._addFileChildren(
  AppLearnRouteChildren,
)

interface AppLearnCurriculumRouteChildren {
  AppLearnCurriculumUnitIdRoute: typeof AppLearnCurriculumUnitIdRoute
}

const AppLearnCurriculumRouteChildren: AppLearnCurriculumRouteChildren = {
  AppLearnCurriculumUnitIdRoute: AppLearnCurriculumUnitIdRoute,
}

const AppLearnCurriculumRouteWithChildren = AppLearnCurriculumRoute._addFileChildren(
  AppLearnCurriculumRouteChildren,
)

interface AppLibraryRouteChildren {
  AppLibraryIdRoute: typeof AppLibraryIdRoute
}

const AppLibraryRouteChildren: AppLibraryRouteChildren = {
  AppLibraryIdRoute: AppLibraryIdRoute,
}

const AppLibraryRouteWithChildren = AppLibraryRoute._addFileChildren(
  AppLibraryRouteChildren,
)

interface AppOsezRouteChildren {
  AppOsezIdRoute: typeof AppOsezIdRoute
  AppOsezPulseRoute: typeof AppOsezPulseRoute
}

const AppOsezRouteChildren: AppOsezRouteChildren = {
  AppOsezIdRoute: AppOsezIdRoute,
  AppOsezPulseRoute: AppOsezPulseRoute,
}

const AppOsezRouteWithChildren =
  AppOsezRoute._addFileChildren(AppOsezRouteChildren)

interface AppPronlabRouteChildren {
  AppPronlabSetIdRoute: typeof AppPronlabSetIdRoute
}

const AppPronlabRouteChildren: AppPronlabRouteChildren = {
  AppPronlabSetIdRoute: AppPronlabSetIdRoute,
}

const AppPronlabRouteWithChildren = AppPronlabRoute._addFileChildren(
  AppPronlabRouteChildren,
)

interface AppTandemRouteChildren {
  AppTandemIdRoute: typeof AppTandemIdRoute
}

const AppTandemRouteChildren: AppTandemRouteChildren = {
  AppTandemIdRoute: AppTandemIdRoute,
}

const AppTandemRouteWithChildren = AppTandemRoute._addFileChildren(
  AppTandemRouteChildren,
)

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRoute
  AppExploreRoute: typeof AppExploreRoute
  AppImmersionRoute: typeof AppImmersionRoute
  AppLearnRoute: typeof AppLearnRouteWithChildren
  AppLibraryRoute: typeof AppLibraryRouteWithChildren
  AppMissionRoute: typeof AppMissionRoute
  AppMoiRoute: typeof AppMoiRoute
  AppOsezRoute: typeof AppOsezRouteWithChildren
  AppPlantRoute: typeof AppPlantRoute
  AppPronlabRoute: typeof AppPronlabRouteWithChildren
  AppTandemRoute: typeof AppTandemRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRoute,
  AppExploreRoute: AppExploreRoute,
  AppImmersionRoute: AppImmersionRoute,
  AppLearnRoute: AppLearnRouteWithChildren,
  AppLibraryRoute: AppLibraryRouteWithChildren,
  AppMissionRoute: AppMissionRoute,
  AppMoiRoute: AppMoiRoute,
  AppOsezRoute: AppOsezRouteWithChildren,
  AppPlantRoute: AppPlantRoute,
  AppPronlabRoute: AppPronlabRouteWithChildren,
  AppTandemRoute: AppTandemRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute,
  ApiAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
