/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppConnectRouteImport } from './routes/_app/connect'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppImmersionRouteImport } from './routes/_app/immersion'
import { Route as AppLearnRouteImport } from './routes/_app/learn'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppMissionRouteImport } from './routes/_app/mission'
import { Route as AppMoiRouteImport } from './routes/_app/moi'
import { Route as AppOsezRouteImport } from './routes/_app/osez'
import { Route as AppPlantRouteImport } from './routes/_app/plant'
import { Route as AppPronlabRouteImport } from './routes/_app/pronlab'
import { Route as AppTandemRouteImport } from './routes/_app/tandem'
import { Route as AppLibraryIdRouteImport } from './routes/_app/library.$id'
import { Route as AppOsezIdRouteImport } from './routes/_app/osez.$id'
import { Route as AppPronlabSetIdRouteImport } from './routes/_app/pronlab.$setId'
import { Route as AppTandemIdRouteImport } from './routes/_app/tandem.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppImmersionRoute = AppImmersionRouteImport.update({
  id: '/immersion',
  path: '/immersion',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionRoute = AppMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AppRoute,
} as any)
const AppMoiRoute = AppMoiRouteImport.update({
  id: '/moi',
  path: '/moi',
  getParentRoute: () => AppRoute,
} as any)
const AppOsezRoute = AppOsezRouteImport.update({
  id: '/osez',
  path: '/osez',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantRoute = AppPlantRouteImport.update({
  id: '/plant',
  path: '/plant',
  getParentRoute: () => AppRoute,
} as any)
const AppPronlabRoute = AppPronlabRouteImport.update({
  id: '/pronlab',
  path: '/pronlab',
  getParentRoute: () => AppRoute,
} as any)
const AppTandemRoute = AppTandemRouteImport.update({
  id: '/tandem',
  path: '/tandem',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIdRoute = AppLibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppOsezIdRoute = AppOsezIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOsezRoute,
} as any)
const AppPronlabSetIdRoute = AppPronlabSetIdRouteImport.update({
  id: '/$setId',
  path: '/$setId',
  getParentRoute: () => AppPronlabRoute,
} as any)
const AppTandemIdRoute = AppTandemIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTandemRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/connect': typeof AppConnectRoute
  '/explore': typeof AppExploreRoute
  '/immersion': typeof AppImmersionRoute
  '/learn': typeof AppLearnRoute
  '/library': typeof AppLibraryRouteWithChildren
  '/mission': typeof AppMissionRoute
  '/moi': typeof AppMoiRoute
  '/osez': typeof AppOsezRouteWithChildren
  '/plant': typeof AppPlantRoute
  '/pronlab': typeof AppPronlabRouteWithChildren
  '/tandem': typeof AppTandemRouteWithChildren
  '/library/$id': typeof AppLibraryIdRoute
  '/osez/$id': typeof AppOsezIdRoute
  '/pronlab/$setId': typeof AppPronlabSetIdRoute
  '/tandem/$id': typeof AppTandemIdRoute
}
export interface FileRoutesByTo {
  '/connect': typeof AppConnectRoute
  '/explore': typeof AppExploreRoute
  '/immersion': typeof AppImmersionRoute
  '/learn': typeof AppLearnRoute
  '/library': typeof AppLibraryRouteWithChildren
  '/mission': typeof AppMissionRoute
  '/moi': typeof AppMoiRoute
  '/osez': typeof AppOsezRouteWithChildren
  '/plant': typeof AppPlantRoute
  '/pronlab': typeof AppPronlabRouteWithChildren
  '/tandem': typeof AppTandemRouteWithChildren
  '/': typeof AppIndexRoute
  '/library/$id': typeof AppLibraryIdRoute
  '/osez/$id': typeof AppOsezIdRoute
  '/pronlab/$setId': typeof AppPronlabSetIdRoute
  '/tandem/$id': typeof AppTandemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/connect': typeof AppConnectRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/immersion': typeof AppImmersionRoute
  '/_app/learn': typeof AppLearnRoute
  '/_app/library': typeof AppLibraryRouteWithChildren
  '/_app/mission': typeof AppMissionRoute
  '/_app/moi': typeof AppMoiRoute
  '/_app/osez': typeof AppOsezRouteWithChildren
  '/_app/plant': typeof AppPlantRoute
  '/_app/pronlab': typeof AppPronlabRouteWithChildren
  '/_app/tandem': typeof AppTandemRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/library/$id': typeof AppLibraryIdRoute
  '/_app/osez/$id': typeof AppOsezIdRoute
  '/_app/pronlab/$setId': typeof AppPronlabSetIdRoute
  '/_app/tandem/$id': typeof AppTandemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/explore'
    | '/immersion'
    | '/learn'
    | '/library'
    | '/mission'
    | '/moi'
    | '/osez'
    | '/plant'
    | '/pronlab'
    | '/tandem'
    | '/library/$id'
    | '/osez/$id'
    | '/pronlab/$setId'
    | '/tandem/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connect'
    | '/explore'
    | '/immersion'
    | '/learn'
    | '/library'
    | '/mission'
    | '/moi'
    | '/osez'
    | '/plant'
    | '/pronlab'
    | '/tandem'
    | '/'
    | '/library/$id'
    | '/osez/$id'
    | '/pronlab/$setId'
    | '/tandem/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/connect'
    | '/_app/explore'
    | '/_app/immersion'
    | '/_app/learn'
    | '/_app/library'
    | '/_app/mission'
    | '/_app/moi'
    | '/_app/osez'
    | '/_app/plant'
    | '/_app/pronlab'
    | '/_app/tandem'
    | '/_app/'
    | '/_app/library/$id'
    | '/_app/osez/$id'
    | '/_app/pronlab/$setId'
    | '/_app/tandem/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/immersion': {
      id: '/_app/immersion'
      path: '/immersion'
      fullPath: '/immersion'
      preLoaderRoute: typeof AppImmersionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mission': {
      id: '/_app/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof AppMissionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/moi': {
      id: '/_app/moi'
      path: '/moi'
      fullPath: '/moi'
      preLoaderRoute: typeof AppMoiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/osez': {
      id: '/_app/osez'
      path: '/osez'
      fullPath: '/osez'
      preLoaderRoute: typeof AppOsezRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plant': {
      id: '/_app/plant'
      path: '/plant'
      fullPath: '/plant'
      preLoaderRoute: typeof AppPlantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pronlab': {
      id: '/_app/pronlab'
      path: '/pronlab'
      fullPath: '/pronlab'
      preLoaderRoute: typeof AppPronlabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tandem': {
      id: '/_app/tandem'
      path: '/tandem'
      fullPath: '/tandem'
      preLoaderRoute: typeof AppTandemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/$id': {
      id: '/_app/library/$id'
      path: '/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof AppLibraryIdRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/_app/osez/$id': {
      id: '/_app/osez/$id'
      path: '/$id'
      fullPath: '/osez/$id'
      preLoaderRoute: typeof AppOsezIdRouteImport
      parentRoute: typeof AppOsezRoute
    }
    '/_app/pronlab/$setId': {
      id: '/_app/pronlab/$setId'
      path: '/$setId'
      fullPath: '/pronlab/$setId'
      preLoaderRoute: typeof AppPronlabSetIdRouteImport
      parentRoute: typeof AppPronlabRoute
    }
    '/_app/tandem/$id': {
      id: '/_app/tandem/$id'
      path: '/$id'
      fullPath: '/tandem/$id'
      preLoaderRoute: typeof AppTandemIdRouteImport
      parentRoute: typeof AppTandemRoute
    }
  }
}

interface AppLibraryRouteChildren {
  AppLibraryIdRoute: typeof AppLibraryIdRoute
}

const AppLibraryRouteChildren: AppLibraryRouteChildren = {
  AppLibraryIdRoute: AppLibraryIdRoute,
}

const AppLibraryRouteWithChildren = AppLibraryRoute._addFileChildren(
  AppLibraryRouteChildren,
)

interface AppOsezRouteChildren {
  AppOsezIdRoute: typeof AppOsezIdRoute
}

const AppOsezRouteChildren: AppOsezRouteChildren = {
  AppOsezIdRoute: AppOsezIdRoute,
}

const AppOsezRouteWithChildren =
  AppOsezRoute._addFileChildren(AppOsezRouteChildren)

interface AppPronlabRouteChildren {
  AppPronlabSetIdRoute: typeof AppPronlabSetIdRoute
}

const AppPronlabRouteChildren: AppPronlabRouteChildren = {
  AppPronlabSetIdRoute: AppPronlabSetIdRoute,
}

const AppPronlabRouteWithChildren = AppPronlabRoute._addFileChildren(
  AppPronlabRouteChildren,
)

interface AppTandemRouteChildren {
  AppTandemIdRoute: typeof AppTandemIdRoute
}

const AppTandemRouteChildren: AppTandemRouteChildren = {
  AppTandemIdRoute: AppTandemIdRoute,
}

const AppTandemRouteWithChildren = AppTandemRoute._addFileChildren(
  AppTandemRouteChildren,
)

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRoute
  AppExploreRoute: typeof AppExploreRoute
  AppImmersionRoute: typeof AppImmersionRoute
  AppLearnRoute: typeof AppLearnRoute
  AppLibraryRoute: typeof AppLibraryRouteWithChildren
  AppMissionRoute: typeof AppMissionRoute
  AppMoiRoute: typeof AppMoiRoute
  AppOsezRoute: typeof AppOsezRouteWithChildren
  AppPlantRoute: typeof AppPlantRoute
  AppPronlabRoute: typeof AppPronlabRouteWithChildren
  AppTandemRoute: typeof AppTandemRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRoute,
  AppExploreRoute: AppExploreRoute,
  AppImmersionRoute: AppImmersionRoute,
  AppLearnRoute: AppLearnRoute,
  AppLibraryRoute: AppLibraryRouteWithChildren,
  AppMissionRoute: AppMissionRoute,
  AppMoiRoute: AppMoiRoute,
  AppOsezRoute: AppOsezRouteWithChildren,
  AppPlantRoute: AppPlantRoute,
  AppPronlabRoute: AppPronlabRouteWithChildren,
  AppTandemRoute: AppTandemRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
