export type LabLevel = "A1" | "A2" | "B1";

export type GrammarTask = {
  id: string;
  prompt: string;
  choices: string[];
  answer: string;
  explanation: string;
  target: string;
  level: LabLevel;
};

export const GRAMMAR_TASKS: GrammarTask[] = [
  { id: "grammar-a1-1", prompt: "Quelle phrase permet de se présenter ?", choices: ["My name is Léa.", "Name my is Léa.", "Is my Léa name."], answer: "My name is Léa.", explanation: "My name is + prénom est une structure de base pour se présenter.", target: "Se présenter", level: "A1" },
  { id: "grammar-a1-2", prompt: "Complétez : “I ___ from Kenya.”", choices: ["am", "is", "are"], answer: "am", explanation: "Avec I, le présent de be est am.", target: "Be avec I", level: "A1" },
  { id: "grammar-a1-3", prompt: "Quelle question demande un lieu ?", choices: ["Where are you?", "Where you are?", "You are where?"], answer: "Where are you?", explanation: "Where + be + sujet forme la question de base sur le lieu.", target: "Question en Where", level: "A1" },

  { id: "grammar-question-1", prompt: "Quelle phrase demande naturellement une recommandation ?", choices: ["What you recommend?", "What do you recommend?", "What are you recommend?"], answer: "What do you recommend?", explanation: "Au présent simple, do porte la structure interrogative.", target: "Question au présent simple", level: "A2" },
  { id: "grammar-question-2", prompt: "Complétez : “I ___ the fish.”", choices: ["will have", "am have", "have to"], answer: "will have", explanation: "I'll have sert à annoncer une commande ou un choix au moment de décider.", target: "I'll have…", level: "A2" },
  { id: "grammar-question-3", prompt: "Quelle formule demande poliment de répéter ?", choices: ["Could you repeat that?", "Could you to repeat that?", "Could repeat you that?"], answer: "Could you repeat that?", explanation: "Après could, on garde la base verbale.", target: "Modal + base verbale", level: "A2" },
  { id: "grammar-question-4", prompt: "Quel passé simple est correct ?", choices: ["Yesterday I walk to the market.", "Yesterday I walked to the market.", "Yesterday I walking to the market."], answer: "Yesterday I walked to the market.", explanation: "Walk est régulier : walked.", target: "Past simple régulier", level: "A2" },
  { id: "grammar-question-5", prompt: "Quelle relance rend le tour de parole à l'autre personne ?", choices: ["What about you?", "What about your?", "What you about?"], answer: "What about you?", explanation: "What about you? est une relance courte et complète.", target: "Relance interactionnelle", level: "A2" },
  { id: "grammar-b1-1", prompt: "Quel connecteur exprime le contraste ? “I enjoyed the course, ___ it was quite intensive.”", choices: ["because", "although", "so"], answer: "although", explanation: "Although introduit ici une idée contrastée avec le fait d'avoir apprécié le cours.", target: "Connecteurs · contraste", level: "B1" },
  { id: "grammar-b1-2", prompt: "Quelle phrase relie correctement une cause et une conséquence ?", choices: ["The bus was delayed, so I arrived late.", "The bus was delayed, because I arrived late.", "The bus was delayed, although I arrived late."], answer: "The bus was delayed, so I arrived late.", explanation: "So introduit la conséquence de la première proposition.", target: "Connecteurs · conséquence", level: "B1" },
  { id: "grammar-b1-3", prompt: "Choisissez la formulation la plus naturelle pour une expérience passée encore pertinente :", choices: ["I have visited Réunion three times.", "I visit Réunion three times.", "I have visit Réunion three times."], answer: "I have visited Réunion three times.", explanation: "Le present perfect relie une expérience passée à la situation présente sans donner de date précise.", target: "Present perfect · expérience", level: "B1" },
  { id: "grammar-b1-4", prompt: "Quelle phrase exprime une possibilité prudente ?", choices: ["This could be the reason.", "This must be the reason.", "This is definitely the reason."], answer: "This could be the reason.", explanation: "Could marque une possibilité plutôt qu'une certitude.", target: "Modalisation · possibilité", level: "B1" },
  { id: "grammar-b1-5", prompt: "Quel relatif convient ? “The place ___ we met was near the harbour.”", choices: ["where", "who", "which people"], answer: "where", explanation: "Where relie un lieu à la proposition qui le décrit.", target: "Proposition relative · lieu", level: "B1" },
  { id: "grammar-question-6", prompt: "Complétez : “Where ___ you staying?”", choices: ["are", "do", "is"], answer: "are", explanation: "Avec be au présent continu, on garde are devant le sujet you.", target: "Question avec be", level: "A2" },
  { id: "grammar-question-7", prompt: "Quelle phrase propose une option polie ?", choices: ["Could we meet at ten?", "Could we to meet at ten?", "Could meet we at ten?"], answer: "Could we meet at ten?", explanation: "Après could, le verbe reste à la base et le sujet vient entre le modal et le verbe.", target: "Could + base verbale", level: "A2" },
  { id: "grammar-question-8", prompt: "Complétez : “I ___ to call you yesterday.”", choices: ["forget", "forgot", "have forget"], answer: "forgot", explanation: "Hier signale une action passée terminée : le past simple de forget est forgot.", target: "Past simple irrégulier", level: "A2" },
  { id: "grammar-question-9", prompt: "Quelle phrase décrit une obligation simple ?", choices: ["I have to leave at six.", "I have leave at six.", "I have to leaving at six."], answer: "I have to leave at six.", explanation: "Have to est suivi de la base verbale.", target: "Have to + base", level: "A2" },
  { id: "grammar-b1-7", prompt: "Quelle phrase exprime une hypothèse réaliste ?", choices: ["If we leave now, we can catch the bus.", "If we left now, we caught the bus.", "If we leave now, we caught the bus."], answer: "If we leave now, we can catch the bus.", explanation: "La première condition relie une situation possible à une conséquence possible.", target: "First conditional", level: "B1" },
  { id: "grammar-b1-8", prompt: "Quelle formulation met en avant une conséquence passée ?", choices: ["As a result, we had to change the plan.", "As a result, we have change the plan.", "As result, we changing the plan."], answer: "As a result, we had to change the plan.", explanation: "As a result introduit la conséquence ; le passé reste cohérent avec had to change.", target: "Cause / conséquence", level: "B1" },
  { id: "grammar-b1-9", prompt: "Quel choix est le plus naturel pour rapporter une information ?", choices: ["She said that the room was ready.", "She said the room is ready yesterday.", "She said that the room ready."], answer: "She said that the room was ready.", explanation: "Le discours rapporté adapte naturellement le temps après said dans ce contexte.", target: "Discours rapporté", level: "B1" },
  { id: "grammar-b1-10", prompt: "Quelle phrase reconnaît une réserve avant de conclure ?", choices: ["Although it is cheaper, it may take longer.", "Because it is cheaper, it may take longer.", "So it is cheaper, although."], answer: "Although it is cheaper, it may take longer.", explanation: "Although construit explicitement le contraste entre avantage et réserve.", target: "Concession", level: "B1" },
  { id: "grammar-b1-6", prompt: "Quelle formulation nuance une opinion ?", choices: ["It is always the best option.", "It can be a useful option in some situations.", "It is the only option."], answer: "It can be a useful option in some situations.", explanation: "Can + in some situations évite une affirmation absolue et rend l'énoncé plus précis.", target: "Nuancer une opinion", level: "B1" },
];

export type ListeningTask = {
  id: string;
  audioText: string;
  question: string;
  choices: string[];
  answer: string;
  detail: string;
  level: LabLevel;
};

export const LISTENING_TASKS: ListeningTask[] = [
  { id: "listen-a1-1", audioText: "Hello, my name is Sam.", question: "Comment s'appelle la personne ?", choices: ["Sam", "Tom", "Maya"], answer: "Sam", detail: "Le prénom est donné immédiatement après my name is.", level: "A1" },
  { id: "listen-a1-2", audioText: "The café is on the left.", question: "Où est le café ?", choices: ["À droite", "À gauche", "Derrière"], answer: "À gauche", detail: "On the left donne la direction utile.", level: "A1" },
  { id: "listen-a1-3", audioText: "I need one ticket to Saint-Pierre, please.", question: "Combien de billets sont demandés ?", choices: ["One", "Two", "Three"], answer: "One", detail: "One ticket indique une seule place.", level: "A1" },

  { id: "listen-1", audioText: "Boarding starts at seven forty at gate twelve.", question: "À quelle porte commence l'embarquement ?", choices: ["Gate 10", "Gate 12", "Gate 20"], answer: "Gate 12", detail: "Le numéro utile arrive en fin de phrase.", level: "A2" },
  { id: "listen-2", audioText: "The restaurant opens at seven, but the kitchen closes at nine.", question: "Quelle information est vraie ?", choices: ["The kitchen opens at nine.", "The restaurant opens at seven.", "The restaurant closes at seven."], answer: "The restaurant opens at seven.", detail: "Le premier repère temporel décrit l'ouverture.", level: "A2" },
  { id: "listen-3", audioText: "These pods are four euros for three.", question: "Combien coûtent trois gousses ?", choices: ["3 euros", "4 euros", "13 euros"], answer: "4 euros", detail: "Le prix indiqué correspond au lot de trois.", level: "A2" },
  { id: "listen-4", audioText: "It's on the second floor, left of the library.", question: "Où se trouve le lieu ?", choices: ["On the ground floor", "On the second floor, left of the library", "Behind the café"], answer: "On the second floor, left of the library", detail: "L'étage et le repère spatial arrivent dans la même phrase.", level: "A2" },
  { id: "listen-b1-1", audioText: "I was going to take the earlier train, but the platform changed, so I waited for the next one.", question: "Pourquoi la personne a-t-elle attendu le train suivant ?", choices: ["The earlier train was cancelled.", "The platform changed.", "The train was too expensive."], answer: "The platform changed.", detail: "L'information importante n'est pas donnée dans la première idée : la décision change après the platform changed.", level: "B1" },
  { id: "listen-b1-2", audioText: "The café is usually quiet in the morning, although it gets crowded around lunchtime.", question: "Quelle nuance décrit le mieux le café ?", choices: ["It is always crowded.", "It is generally quiet but busier at lunchtime.", "It is closed in the morning."], answer: "It is generally quiet but busier at lunchtime.", detail: "Usually et although obligent à combiner deux informations plutôt qu'à retenir un seul mot.", level: "B1" },
  { id: "listen-b1-3", audioText: "We could meet outside the station at six, unless your flight is delayed. In that case, send me a message.", question: "Que doit faire la personne si le vol est retardé ?", choices: ["Wait outside at six.", "Go straight to the hotel.", "Send a message."], answer: "Send a message.", detail: "La condition modifie le plan initial ; l'écoute doit suivre la relation entre unless et in that case.", level: "B1" },
  { id: "listen-b1-4", audioText: "The manager said the workshop was useful, but she felt the final exercise needed more time.", question: "Quelle opinion correspond au message ?", choices: ["The whole workshop was useless.", "The workshop was useful, with a reservation about the final exercise.", "The final exercise was the best part."], answer: "The workshop was useful, with a reservation about the final exercise.", detail: "Le but est d'entendre à la fois l'évaluation positive et la réserve introduite par but.", level: "B1" },
  { id: "listen-b1-5", audioText: "If we leave before eight, we should have enough time to stop for coffee before the museum opens.", question: "Pourquoi partir avant huit heures ?", choices: ["To arrive after the museum closes.", "To have time for a coffee stop before opening.", "Because the museum opens at eight."], answer: "To have time for a coffee stop before opening.", detail: "La réponse exige de relier condition, temps disponible et objectif.", level: "B1" },
  { id: "listen-5", audioText: "The pharmacy is opposite the post office, next to the small bakery.", question: "Quel repère aide le plus à trouver la pharmacie ?", choices: ["The large hotel", "The post office and small bakery", "The bus depot"], answer: "The post office and small bakery", detail: "Il faut combiner les deux repères spatiaux plutôt que retenir seulement opposite.", level: "A2" },
  { id: "listen-6", audioText: "I'd like a room for two nights, arriving on Friday and leaving on Sunday.", question: "Combien de nuits la personne réserve-t-elle ?", choices: ["One", "Two", "Three"], answer: "Two", detail: "Friday to Sunday corresponds here to two nights.", level: "A2" },
  { id: "listen-7", audioText: "Could you send me the address before lunch? I need to check the route.", question: "Pourquoi la personne demande-t-elle l'adresse ?", choices: ["To change the meeting", "To check the route", "To order lunch"], answer: "To check the route", detail: "Le second énoncé donne la raison de la demande.", level: "A2" },
  { id: "listen-8", audioText: "The blue bag is mine, but the smaller one belongs to Maya.", question: "À qui appartient le petit sac ?", choices: ["The speaker", "Maya", "Noah"], answer: "Maya", detail: "Le contraste entre mine et belongs to Maya porte la réponse.", level: "A2" },
  { id: "listen-b1-7", audioText: "We can leave at nine if the weather stays clear, but if the wind picks up, I'd rather wait until late morning.", question: "Quelle est la condition qui ferait changer le plan ?", choices: ["A late breakfast", "Stronger wind", "A busy market"], answer: "Stronger wind", detail: "The plan is conditional twice; the decisive trigger is if the wind picks up.", level: "B1" },
  { id: "listen-b1-8", audioText: "I don't mind taking the longer route as long as we can avoid the roadworks near the harbour.", question: "Quelle préférence est exprimée ?", choices: ["The shortest route at all costs", "A longer route is acceptable if it avoids the roadworks.", "The harbour should be closed."], answer: "A longer route is acceptable if it avoids the roadworks.", detail: "As long as introduces the condition attached to accepting the longer route.", level: "B1" },
  { id: "listen-b1-9", audioText: "The first proposal would be cheaper, however it would also mean fewer staff on site.", question: "Quel est le compromis principal ?", choices: ["Higher cost and more staff", "Lower cost with fewer staff", "No change in staffing"], answer: "Lower cost with fewer staff", detail: "However signals a trade-off rather than a simple yes/no evaluation.", level: "B1" },
  { id: "listen-b1-10", audioText: "She said she could join us after work, provided the meeting finishes on time.", question: "Dans quelle condition peut-elle rejoindre le groupe ?", choices: ["If lunch starts early", "If the meeting finishes on time", "If the shop closes late"], answer: "If the meeting finishes on time", detail: "Provided introduces the condition that controls her availability.", level: "B1" },
  { id: "listen-b1-6", audioText: "I thought the meeting was on Thursday, but I've just checked the calendar and it is actually on Friday afternoon.", question: "Qu'est-ce qui a changé pour la personne ?", choices: ["The meeting was cancelled.", "The meeting date was corrected from Thursday to Friday afternoon.", "The meeting moved from Friday to Thursday."], answer: "The meeting date was corrected from Thursday to Friday afternoon.", detail: "La compréhension repose sur le contraste entre thought et actually.", level: "B1" },
];

export type WritingPrompt = {
  id: string;
  title: string;
  situation: string;
  task: string;
  model: string;
  checks: Array<{ id: string; label: string }>;
  level: LabLevel;
};

export const WRITING_PROMPTS: WritingPrompt[] = [
  { id: "write-a1-1", title: "Se présenter simplement", situation: "Vous rencontrez quelqu'un pour la première fois.", task: "Écrivez 2 à 3 phrases pour donner votre nom, votre ville et une chose que vous aimez.", model: "Hi, I'm Sam. I live in Nairobi. I like music.", checks: [{ id: "a1-name", label: "J'ai donné mon nom." }, { id: "a1-place", label: "J'ai indiqué où je vis." }, { id: "a1-interest", label: "J'ai ajouté une préférence." }], level: "A1" },
  { id: "write-a1-2", title: "Un message pratique", situation: "Vous devez confirmer un rendez-vous très simple.", task: "Écrivez 2 à 3 phrases avec l'heure et le lieu.", model: "Hi. See you at three at the café. See you then.", checks: [{ id: "a1-time", label: "J'ai donné l'heure." }, { id: "a1-place", label: "J'ai donné le lieu." }, { id: "a1-close", label: "J'ai terminé simplement." }], level: "A1" },
  { id: "write-a1-3", title: "Demander une information", situation: "Vous écrivez à quelqu'un pour demander où se trouve un lieu.", task: "Écrivez 2 à 3 phrases avec une salutation et une question claire.", model: "Hi. Where is the library? Is it near the café?", checks: [{ id: "a1-greet", label: "J'ai salué." }, { id: "a1-question", label: "J'ai posé une question claire." }, { id: "a1-followup", label: "J'ai ajouté une petite relance." }], level: "A1" },

  { id: "write-after-class", title: "Un message après le cours", situation: "Vous écrivez à un collègue anglophone pour confirmer l'heure du déjeuner.", task: "Écrivez 2 à 4 phrases en anglais. Confirmez l'heure, proposez un lieu et terminez poliment.", model: "Hi Noah, lunch at 12:30 at the café? See you there!", checks: [{ id: "check-info", label: "J'ai donné une information claire." }, { id: "check-place", label: "J'ai proposé ou confirmé un lieu." }, { id: "check-close", label: "J'ai terminé avec une formule naturelle." }], level: "A2" },
  { id: "write-recommendation", title: "Une recommandation simple", situation: "Un ami vous demande quoi manger à Saint-Pierre.", task: "Écrivez une recommandation courte avec un plat et une raison.", model: "I'd recommend the catch of the day. It's fresh and simple.", checks: [{ id: "check-choice", label: "J'ai recommandé quelque chose de précis." }, { id: "check-reason", label: "J'ai donné une raison compréhensible." }, { id: "check-natural", label: "Ma phrase reste courte et naturelle." }], level: "A2" },
  { id: "write-b1-1", title: "Recommander entre deux options", situation: "Deux amis hésitent entre deux activités pour le week-end.", task: "Écrivez 5 à 7 phrases en expliquant laquelle vous recommandez, selon quel critère, et reconnaissez au moins une limite de votre choix.", model: "I'd recommend the coastal walk because it is more flexible for a short afternoon. The market is livelier, but it takes longer to reach, so the walk seems more practical today.", checks: [{ id: "b1-choice", label: "J'ai comparé au moins deux options." }, { id: "b1-reason", label: "J'ai donné un critère et une raison." }, { id: "b1-counterpoint", label: "J'ai reconnu une limite ou un avantage de l'autre option." }, { id: "b1-connector", label: "J'ai relié mes idées avec un connecteur." }], level: "B1" },
  { id: "write-b1-2", title: "Signaler un problème avec une solution", situation: "Vous écrivez à un hébergement : la chambre est correcte mais un équipement ne fonctionne pas.", task: "Écrivez un message de 6 à 8 phrases : décrivez le problème, expliquez son impact et proposez une solution réaliste.", model: "The room is comfortable, but the shower is not working properly. It is difficult to get ready in the morning. Could someone check it today? If that is not possible, another room would be helpful.", checks: [{ id: "b1-problem", label: "J'ai décrit le problème avec précision." }, { id: "b1-impact", label: "J'ai expliqué la conséquence." }, { id: "b1-solution", label: "J'ai proposé une solution." }, { id: "b1-tone", label: "Le ton reste clair et coopératif." }], level: "B1" },
  { id: "write-b1-3", title: "Prendre position sans tout simplifier", situation: "Une association demande votre avis sur l'ouverture plus tardive d'un lieu culturel.", task: "Écrivez 6 à 9 phrases avec votre position, deux raisons, une réserve et une proposition.", model: "I think opening later would help people who work during the day. It could also make the centre more useful in the evening. However, extra staff would cost more, so I would suggest starting with two late evenings a week.", checks: [{ id: "b1-position", label: "J'ai formulé une position claire." }, { id: "b1-reasons", label: "J'ai donné au moins deux raisons." }, { id: "b1-nuance", label: "J'ai reconnu une contrainte ou une réserve." }, { id: "b1-proposal", label: "J'ai terminé par une proposition." }], level: "B1" },
  { id: "write-after-class-2", title: "Déplacer un rendez-vous", situation: "Votre collègue vous propose une heure qui ne convient pas.", task: "Écrivez 3 à 5 phrases : expliquez la contrainte, proposez une autre heure et demandez confirmation.", model: "I can't make three, but I could do four thirty. Would that work for you?", checks: [{ id: "a2-constraint", label: "J'ai expliqué la contrainte." }, { id: "a2-option", label: "J'ai proposé une autre heure." }, { id: "a2-confirm", label: "J'ai demandé confirmation." }], level: "A2" },
  { id: "write-after-class-3", title: "Donner une indication utile", situation: "Une personne vous écrit pour demander comment rejoindre un lieu.", task: "Écrivez 3 à 5 phrases avec deux étapes, un repère et une estimation de temps.", model: "Go straight past the market, then turn left at the pharmacy. It's about five minutes from there.", checks: [{ id: "a2-step", label: "J'ai donné au moins deux étapes." }, { id: "a2-landmark", label: "J'ai utilisé un repère." }, { id: "a2-time", label: "J'ai donné une estimation." }], level: "A2" },
  { id: "write-b1-5", title: "Répondre à une proposition", situation: "On vous propose une activité qui vous plaît mais présente une contrainte d'horaire.", task: "Écrivez 6 à 8 phrases : dites ce qui vous convient, exprimez la contrainte, faites une contre-proposition et gardez un ton coopératif.", model: "I'd like to join, but I won't be free before six. Could we start later? If that is too late for everyone, I could join for the second part.", checks: [{ id: "b1-positive", label: "J'ai reconnu l'aspect positif." }, { id: "b1-constraint", label: "J'ai expliqué ma contrainte." }, { id: "b1-counter", label: "J'ai fait une contre-proposition." }, { id: "b1-cooperative", label: "J'ai gardé une ouverture." }], level: "B1" },
  { id: "write-b1-6", title: "Résumer une décision", situation: "Votre équipe vient de choisir une solution et une personne absente doit savoir quoi faire.", task: "Écrivez 6 à 8 phrases en distinguant décision, raison et prochaine étape.", model: "We decided to meet on Friday because more people are available then. The room stays the same, and I will send the final time this afternoon.", checks: [{ id: "b1-decision", label: "La décision est claire." }, { id: "b1-reason", label: "J'ai donné la raison principale." }, { id: "b1-next", label: "J'ai indiqué la prochaine étape." }], level: "B1" },
  { id: "write-b1-4", title: "Reformuler pour un tiers", situation: "Un collègue n'a pas lu un message important sur un changement d'horaire.", task: "Écrivez 5 à 7 phrases en transmettant l'essentiel sans recopier le message d'origine.", model: "The meeting has moved to Friday afternoon. The room is the same, but we should arrive ten minutes earlier because the building closes at six.", checks: [{ id: "b1-essential", label: "J'ai gardé les informations essentielles." }, { id: "b1-rephrase", label: "J'ai reformulé plutôt que copié." }, { id: "b1-detail", label: "J'ai gardé les détails utiles." }], level: "B1" },
];

export function speakSyntheticEnglish(text: string): void {
  if (typeof window === "undefined" || !("speechSynthesis" in window)) return;
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.lang = "en-GB";
  utterance.rate = 0.9;
  window.speechSynthesis.cancel();
  window.speechSynthesis.speak(utterance);
}
